# https://docs.pulsir.net/home
database: "flatfile" # mongo | flatfile
mongo-uri: ""
redis:
  host: ""
  port: 6379
  auth: false
  password: ""
allow-sync: true
sync-system: "bungee" # bungee | redis

message-format: "legacy" # legacy | modern

force-vanish: true
staff-bar: true

join-message: true
quit-message: true

report-cooldown: 60
request-cooldown: 60

delete-on-restore: true
allow-staff-spy: false

inventory-on-freeze: false
freeze-chat: true

spy:
  messages: true
  commands: true

staff-items:
  compass:
    item: "COMPASS"
    enchanted: false
    enchants:
      - ""
    name: "&cTeleportation Compass"
    lore:
      - ""
      - "&fRight click to go through walls"
      - ""
    slot: 0
    enabled: true
  inspect:
    item: "BOOK"
    enchanted: false
    enchants:
      - ""
    name: "&cInspection Book"
    lore:
      - ""
      - "&fRight click to view player inventory."
      - ""
    slot: 1
    enabled: true
  freeze:
    item: "ICE"
    enchanted: false
    enchants:
      - ""
    name: "&cFreeze Player"
    lore:
      - ""
      - "&fRight click to freeze player."
      - ""
    slot: 2
    enabled: true
  random:
    item: "CLOCK"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player."
      - ""
    slot: 8
    enabled: true
  online:
    item: "DIAMOND"
    enchanted: false
    enchants:
      - ""
    name: "&cOnline Staff"
    lore:
      - ""
      - "&fRight click to view online staff."
      - ""
    slot: 7
    enabled: true
  wand:
    item: "WOODEN_AXE"
    enchanted: false
    enchants:
      - ""
    name: "&cWand"
    lore:
      - ""
      - "&fRight click to do the magic."
      - ""
    slot: 6
    enabled: true

online-inventory:
  title: "&cOnline Staff"
  size: 54
  overlay: true
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  item-format:
    name: "&d{player}"
    lore:
      - ""
      - "&dVanished&f: {vanished}"
      - ""

freeze-inventory:
  title: "&cFrozen Inventory"
  size: 9
  overlay: true
  overlay-item: "PURPLE_STAINED_GLASS_PANE"
  items:
    1:
      item: "BOOK"
      name: "&cYou are &c&lFROZEN"
      lore:
        - ""
        - "&cPlease join our discord discord.gg/server"
        - "&cand create a freeze ticket."
        - "&cYou have 3 minutes."
        - ""
      slot: 4

inspect-inventory:
  title: "&cInspect Inventory"
  statistics-item: true
  item: "GLISTERING_MELON_SLICE"
  name: "&a{player}'s Inventory"
  lore:
    - ""
    - "&f{health}&d/&f{health_max}"
    - "&f{hunger}&d/&f20"
    - "&fGamemode&d: &f{gamemode}"
    - ""