database: "flatfile" # mongo | flatfile
mongo-uri: ""
redis:
  host: ""
  port: 6379
  auth: false
  password: ""
allow-sync: true
sync-system: "bungee" # bungee | redis
server-name: "Hub"

message-format: "legacy" # legacy | modern

online-players: "bukkit" # bukkit | custom

staff-bar: true
staff-bar-visibility: "staff" # staff | vanish | both

vanish-effects:
  - "NIGHT_VISION"
staff-effects:
  - "NIGHT_VISION"

force-vanish: true

join-message: true
quit-message: true

silent-chests: true

report-cooldown: 60
request-cooldown: 60

delete-on-restore: true
allow-staff-spy: false

inventory-on-freeze: false
freeze-chat: true
freeze-blocked-commands:
  - "/tpa"

chat-filter: true
filter-messages:
  - "kys"
  - "faggot"

spy:
  messages: true
  commands: true

staff-items:
  compass:
    item: "COMPASS"
    enchanted: false
    enchants:
      - ""
    name: "&cTeleportation Compass"
    lore:
      - ""
      - "&fRight click to go through walls"
      - ""
    slot: 0
    enabled: true
  inspect:
    item: "BOOK"
    enchanted: false
    enchants:
      - ""
    name: "&cInspection Book"
    lore:
      - ""
      - "&fRight click to view player inventory."
      - ""
    slot: 1
    enabled: true
  freeze:
    item: "ICE"
    enchanted: false
    enchants:
      - ""
    name: "&cFreeze Player"
    lore:
      - ""
      - "&fRight click to freeze player."
      - ""
    slot: 2
    enabled: true
  random:
    item: "CLOCK"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player."
      - ""
    slot: 8
    enabled: true
  online:
    item: "DIAMOND"
    enchanted: false
    enchants:
      - ""
    name: "&cOnline Staff"
    lore:
      - ""
      - "&fRight click to view online staff."
      - ""
    slot: 7
    enabled: true
  wand:
    item: "WOODEN_AXE"
    enchanted: false
    enchants:
      - ""
    name: "&cWand"
    lore:
      - ""
      - "&fRight click to do the magic."
      - ""
    slot: 6
    enabled: true
  random-miners:
    item: "DIAMOND_PICKAXE"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Miner Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player, who is mining."
      - ""
    slot: 4
    y-level: 45
    enabled: true
  random-fighter:
    item: "DIAMOND_SWORD"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Fighter Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player, who is fighting."
      - ""
    slot: 5
    enabled: true
  vanish:
    item: "LIME_DYE"
    enchanted: false
    enchants:
      - ""
    name: "&aEnable Vanish"
    lore:
      - ""
      - "&fRight click to enable your vanish."
      - ""
    slot: 3
    enabled: true
  unvanish:
    item: "RED_DYE"
    enchanted: false
    enchants:
      - ""
    name: "&cDisable Vanish"
    lore:
      - ""
      - "&fRight click to disable your vanish."
      - ""

online-inventory:
  title: "&cOnline Staff"
  size: 54
  overlay: true
  slot-overlay: false
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  slots: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  item-format:
    name: "&d{player}"
    lore:
      - ""
      - "&dVanished&f: {vanished}"
      - "&dSession Time&f: {session_time}"
      - ""

last-inventory:
  title: "&cLast Inventory"
  size: 54
  overlay: true
  slot-overlay: false
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  slots: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  armor-slots: [3,4,6,7]
  off-hand-slot: 5

freeze-inventory:
  title: "&cFrozen Inventory"
  size: 9
  overlay: true
  overlay-item: "PURPLE_STAINED_GLASS_PANE"
  items:
    1:
      item: "BOOK"
      name: "&cYou are &c&lFROZEN"
      lore:
        - ""
        - "&cPlease join our discord discord.gg/server"
        - "&cand create a freeze ticket."
        - "&cYou have 3 minutes."
        - ""
      slot: 4

inspect-inventory:
  title: "&cInspect Inventory"
  statistics-item: true
  item: "GLISTERING_MELON_SLICE"
  name: "&a{player}'s Inventory"
  lore:
    - ""
    - "&f{health}&d/&f{health_max}"
    - "&f{hunger}&d/&f20"
    - "&fGamemode&d: &f{gamemode}"
    - ""

silent-inventory:
  chest-title: "&7Silent Chest"
  enderchest-title: "&7Silent EnderChest"
  shulker-title: "&7Shulker Box"

clear-chat:
  lines: 200

mine-alert:
  enabled: true
  block-trigger:
    - "DIAMOND_ORE"