database: "mongo" # mongo | flatfile
mongo-uri: "mongodb://198.50.209.162:45235/"
bungee: true

force-vanish: true
staff-bar: true

join-message: true
quit-message: true

report-cooldown: 60
request-cooldown: 60

delete-on-restore: true

staff-items:
  compass:
    item: "COMPASS"
    enchanted: false
    enchants:
      - ""
    name: "<red>Teleportation Compass"
    lore:
      - ""
      - "<white>Right click to go through walls"
      - ""
    slot: 0
    enabled: true
  inspect:
    item: "BOOK"
    enchanted: false
    enchants:
      - ""
    name: "<red>Inspection Book"
    lore:
      - ""
      - "<white>Right click to view player inventory."
      - ""
    slot: 1
    enabled: true
  freeze:
    item: "ICE"
    enchanted: false
    enchants:
      - ""
    name: "<red>Freeze Player"
    lore:
      - ""
      - "<white>Right click to freeze player."
      - ""
    slot: 2
    enabled: true
  random:
    item: "CLOCK"
    enchanted: false
    enchants:
      - ""
    name: "<red>Random Teleport"
    lore:
      - ""
      - "<white>Right click to teleport to random player."
      - ""
    slot: 8
    enabled: true
  online:
    item: "DIAMOND"
    enchanted: false
    enchants:
      - ""
    name: "<red>Online Staff"
    lore:
      - ""
      - "<white>Right click to view online staff."
      - ""
    slot: 7
    enabled: true
  wand:
    item: "WOODEN_AXE"
    enchanted: false
    enchants:
      - ""
    name: "<red>Wand"
    lore:
      - ""
      - "<white>Right click to do the magic."
      - ""
    slot: 6
    enabled: true

online-inventory:
  title: "<red>Online Staff"
  size: 54
  overlay: true
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  item-format:
    name: "<light_purple>{player}"
    lore:
      - ""
      - "<light_purple>Vanished<white>: {vanished}"
      - ""

freeze-inventory:
  title: "<red>Frozen Inventory"
  size: 9
  overlay: true
  overlay-item: "PURPLE_STAINED_GLASS_PANE"
  items:
    1:
      item: "BOOK"
      name: "<red>You are <bold>FROZEN"
      lore:
        - ""
        - "<red>Please join our discord discord.gg/server"
        - "<red>and create a freeze ticket."
        - "<red>You have 3 minutes."
        - ""
      slot: 4

inspect-inventory:
  title: "<red>Inspect Inventory"
  statistics-item: true
  item: "GLISTERING_MELON_SLICE"
  name: "<green>{player}'s Inventory"
  lore:
    - ""
    - "<white>{health}<light_purple>/<white>{health_max}"
    - "<white>{hunger}<light_purple>/<white>20"
    - "<white>Gamemode<light_purple>: <white>{gamemode}"
    - ""