license-key: "license_key"

# Database where every data will be saved
database: "flatfile" # mongo | mysql | flatfile
mongo-uri: ""
mysql:
  host: ""
  port: 3306
  database: ""
  auth:
    username: ""
    password: ""
redis:
  host: ""
  port: 6379
  auth: false
  password: ""
allow-sync: true

# Bungee - Staff chat messages will be sent through bungeecord
# Redis - Staff chat messages will be sent through redis (best if you have multiple proxies)
sync-system: "bungee" # bungee | redis
server-name: "Hub"

# Legacy - Supports old style of colors such as &5, &6 and so on.
# Modern - Supports new way of colors such as <red>, <#00FF00>
message-format: "legacy" # legacy | modern

# Bukkit - Counts all players on server
# Custom - Counts all players on server, however without vanished ones.
online-players: "bukkit" # bukkit | custom

# Should staff bar be enabled
staff-bar: true

# Staff - Staff bar will be only enabled if user is in staff mode.
# Vanish - Staff bar will be only enabled if user is in vanish mode.
# Both - Staff bar will be enabled if user is either in vanish or staff mode.
staff-bar-visibility: "staff" # staff | vanish | both

# Effects which player, who is in vanish will receive.
vanish-effects:
  - "NIGHT_VISION"

# Effects which player, who is in staff mode will receive.
staff-effects:
  - "NIGHT_VISION"

# Should all staff members, who join on server be put automatically in vanish.
force-vanish: true

# Should staff members receive a message when another staff joins the server
join-message: true

# Should staff members receive a message when another staff leaves the server
quit-message: true

# Should staff members be only allowed to open a chest in silent (not sound or animation will be presented)
silent-chests: true

# Should players receive a captcha on join (Inventory where they have to click). ONLY FOR NEW PLAYERS
captcha-on-join: true

# Cooldown each player will have to wait until reporting player again.
report-cooldown: 60

# Cooldown each player will have to wait until requesting support again.
request-cooldown: 60

# Should inventory be deleted from database straight away after restoring death player
delete-on-restore: true

# Should staff be allowed to spy on players messages or commands
allow-staff-spy: false

# Should inventory with an item called You are frozen be open whenever player will be frozen
inventory-on-freeze: false

# Should freeze chat be enabled where ONLY staff members and frozen player can communicate
freeze-chat: true

# Commands which frozen player cannot execute
freeze-blocked-commands:
  - "/tpa"

# Commands which player cannot execute
blocked-commands:
  - "plugin"
  - "pl"
  - "plugins"

# Should Lunar filter a chat from banned words
chat-filter: true
filter-messages:
  1:
    message: "nigger"
    command: "tempmute {player} 30d racism -s"
  2:
    message: "faggot"
    command: "tempmute {player} 30d homophobia -s"

spy:
  # Should staff be allowed to spy on player messages
  messages: true
  # Should staff be allowed to spy on player commands
  commands: true

staff-items:
  compass:
    item: "COMPASS"
    enchanted: false
    enchants:
      - ""
    name: "&cTeleportation Compass"
    lore:
      - ""
      - "&fRight click to go through walls"
      - ""
    slot: 0
    enabled: true
  inspect:
    item: "BOOK"
    enchanted: false
    enchants:
      - ""
    name: "&cInspection Book"
    lore:
      - ""
      - "&fRight click to view player inventory."
      - ""
    slot: 1
    enabled: true
  freeze:
    item: "ICE"
    enchanted: false
    enchants:
      - ""
    name: "&cFreeze Player"
    lore:
      - ""
      - "&fRight click to freeze player."
      - ""
    slot: 2
    enabled: true
  random:
    item: "CLOCK"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player."
      - ""
    slot: 8
    enabled: true
  online:
    item: "DIAMOND"
    enchanted: false
    enchants:
      - ""
    name: "&cOnline Staff"
    lore:
      - ""
      - "&fRight click to view online staff."
      - ""
    slot: 7
    enabled: true
  wand:
    item: "WOODEN_AXE"
    enchanted: false
    enchants:
      - ""
    name: "&cWand"
    lore:
      - ""
      - "&fRight click to do the magic."
      - ""
    slot: 6
    enabled: true
  random-miners:
    item: "DIAMOND_PICKAXE"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Miner Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player, who is mining."
      - ""
    slot: 4
    y-level: 45
    enabled: true
  random-fighter:
    item: "DIAMOND_SWORD"
    enchanted: false
    enchants:
      - ""
    name: "&cRandom Fighter Teleport"
    lore:
      - ""
      - "&fRight click to teleport to random player, who is fighting."
      - ""
    slot: 5
    enabled: true
  vanish:
    item: "LIME_DYE"
    enchanted: false
    enchants:
      - ""
    name: "&aEnable Vanish"
    lore:
      - ""
      - "&fRight click to enable your vanish."
      - ""
    slot: 3
    enabled: true
  unvanish:
    item: "RED_DYE"
    enchanted: false
    enchants:
      - ""
    name: "&cDisable Vanish"
    lore:
      - ""
      - "&fRight click to disable your vanish."
      - ""

online-inventory:
  title: "&cOnline Staff"
  size: 54
  overlay: true
  slot-overlay: false
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  slots: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  item-format:
    name: "&d{player}"
    lore:
      - ""
      - "&dVanished&f: {vanished}"
      - "&dSession Time&f: {session_time}"
      - ""

last-inventory:
  title: "&cLast Inventory"
  size: 54
  overlay: true
  slot-overlay: false
  overlay-item: "GRAY_STAINED_GLASS_PANE"
  slots: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]
  armor-slots: [3,4,6,7]
  off-hand-slot: 5

freeze-inventory:
  title: "&cFrozen Inventory"
  size: 9
  overlay: true
  overlay-item: "PURPLE_STAINED_GLASS_PANE"
  items:
    1:
      item: "BOOK"
      name: "&cYou are &c&lFROZEN"
      lore:
        - ""
        - "&cPlease join our discord discord.gg/server"
        - "&cand create a freeze ticket."
        - "&cYou have 3 minutes."
        - ""
      slot: 4

inspect-inventory:
  title: "&cInspect Inventory"
  statistics-item: true
  item: "GLISTERING_MELON_SLICE"
  name: "&a{player}'s Inventory"
  lore:
    - ""
    - "&f{health}&d/&f{health_max}"
    - "&f{hunger}&d/&f20"
    - "&fGamemode&d: &f{gamemode}"
    - ""

silent-inventory:
  chest-title: "&7Silent Chest"
  enderchest-title: "&7Silent EnderChest"
  shulker-title: "&7Shulker Box"

captcha-inventory:
  title: "&cCaptcha Verification"
  size: 27
  items:
    confirm:
      item: "GREEN_WOOL"
      name: "&aClick me!"
      lore:
        - "&6To enter the pearly gates"
    failure:
      item: "RED_WOOL"
      name: "&cDon't click me!"
      lore:
        - "&4OR ELSE"

world-inventory:
  title: "&aWorld &7Inventory"
  size: 9
  items:
    1:
      item: "GRASS_BLOCK"
      name: "&aWorld"
      lore:
        - ""
        - "&7Click to teleport to world"
        - ""
      slot: 0
      world: "world"
    2:
      item: "NETHERRACK"
      name: "&cNether"
      lore:
        - ""
        - "&7Click to teleport to nether"
        - ""
      slot: 4
      world: "world_nether"
    3:
      item: "END_PORTAL_FRAME"
      name: "&dThe End"
      lore:
        - ""
        - "&7Click to teleport to the end"
        - ""
      slot: 8
      world: "world_the_end"

clear-chat:
  lines: 200

mine-alert:
  enabled: true
  detect-amount: true
  block-trigger:
    - "DIAMOND_ORE"