name: Lunar
version: '${version}'
main: net.pulsir.lunar.Lunar
api-version: '1.20'
author: PulsirORG
website: https://pulsir.net/
softdepend: [PlaceholderAPI]
commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  ownerchat:
    aliases: [oc]
  staff:
    aliases: [sc, mod]
  lunar:
    aliases: [plugin]
  vanish:
    aliases: [v]
  freeze:
    aliases: [ss]
  inspect:
    aliases: [invsee]
  broadcast:
    aliases: [alert]
  report:
    aliases: [helpop]
  request:
  restore:
    aliases: [inventoryrestore, restoreinventory]
  spy:
  freezechat:
    aliases: [frozenchat]
  clearchat:
    aliases: [chatclear, cc]
  chat:
  lunarplugin:
    aliases: [lunar]