name: Lunar
version: '${version}'
main: net.pulsir.lunar.Lunar
api-version: '1.20'
commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  ownerchat:
    aliases: [oc]
  staff:
    aliases: [sc, mod]